version: 0.1.0
name: YahooAPI
description: description
timeoutSeconds: 180
aggregatorLogic:
  name: aggregator-YahooAPI
  file: aggregator-logic.js
genericLogics:
  - name: generic-1-YahooAPI
    file: 1.js

